line-length = 88
indent-width = 4

target-version = "py312"

[lint]
select = ["E", "F", "UP", "RUF", "RET", "I", "C90", "A", "B", "SIM"]
ignore = []
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
